name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    # necessary for windows?
    shell: bash
    
jobs:
  build:

    strategy:
      matrix:
        node-version: [20.x]
        OS: [windows-latest]

    runs-on: ${{ matrix.OS }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --include=dev
    - run: cd client && npm install --include=dev && cd ..
    - run: cd server && npm install --include=dev && cd ..
    - run: npm run test-compile
    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - run: npm test
      if: runner.os != 'Linux'
